# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FRIDAYUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FridayUI(object):
    def setupUi(self, FridayUI):
        FridayUI.setObjectName("FridayUI")
        FridayUI.resize(914, 550)
        self.centralwidget = QtWidgets.QWidget(FridayUI)
        self.centralwidget.setObjectName("centralwidget")
        self.Fridayui = QtWidgets.QLabel(self.centralwidget)
        self.Fridayui.setGeometry(QtCore.QRect(0, 0, 921, 541))
        self.Fridayui.setText("")
        self.Fridayui.setPixmap(QtGui.QPixmap("assets/Friday.gif"))
        self.Fridayui.setScaledContents(True)
        self.Fridayui.setAlignment(QtCore.Qt.AlignCenter)
        self.Fridayui.setObjectName("Fridayui")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 470, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 106);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 470, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 411, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("assets/Loading.gif"))
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius:none;\n")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(680, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background: transparent;\n"
"border-radius:none;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        FridayUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FridayUI)
        self.statusbar.setObjectName("statusbar")
        FridayUI.setStatusBar(self.statusbar)

        self.retranslateUi(FridayUI)
        QtCore.QMetaObject.connectSlotsByName(FridayUI)

    def retranslateUi(self, FridayUI):
        _translate = QtCore.QCoreApplication.translate
        FridayUI.setWindowTitle(_translate("FridayUI", "MainWindow"))
        self.pushButton.setText(_translate("FridayUI", "RUN"))
        self.pushButton_2.setText(_translate("FridayUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FridayUI = QtWidgets.QMainWindow()
    ui = Ui_FridayUI()
    ui.setupUi(FridayUI)
    FridayUI.show()
    sys.exit(app.exec_())
